/* Generated By:JavaCC: Do not edit this line. SelectorParserConstants.java */
package org.codehaus.activemq.selector.mockrunner;

/**
 * Alwin Ibba: Changed package
 */
public interface SelectorParserConstants {

    int EOF = 0;
    int LINE_COMMENT = 6;
    int BLOCK_COMMENT = 7;
    int NOT = 8;
    int AND = 9;
    int OR = 10;
    int BETWEEN = 11;
    int LIKE = 12;
    int ESCAPE = 13;
    int IN = 14;
    int IS = 15;
    int TRUE = 16;
    int FALSE = 17;
    int NULL = 18;
    int INTEGER_LITERAL = 19;
    int FLOATING_POINT_LITERAL = 20;
    int EXPONENT = 21;
    int STRING_LITERAL = 22;
    int ID = 23;

    int DEFAULT = 0;

    String[] tokenImage = {
        "<EOF>",
        "\" \"",
        "\"\\t\"",
        "\"\\n\"",
        "\"\\r\"",
        "\"\\f\"",
        "<LINE_COMMENT>",
        "<BLOCK_COMMENT>",
        "\"NOT\"",
        "\"AND\"",
        "\"OR\"",
        "\"BETWEEN\"",
        "\"LIKE\"",
        "\"ESCAPE\"",
        "\"IN\"",
        "\"IS\"",
        "\"TRUE\"",
        "\"FALSE\"",
        "\"NULL\"",
        "<INTEGER_LITERAL>",
        "<FLOATING_POINT_LITERAL>",
        "<EXPONENT>",
        "<STRING_LITERAL>",
        "<ID>",
        "\"=\"",
        "\"<>\"",
        "\">\"",
        "\">=\"",
        "\"<\"",
        "\"<=\"",
        "\"(\"",
        "\",\"",
        "\")\"",
        "\"+\"",
        "\"-\"",
        "\"*\"",
        "\"/\"",
        "\"%\"",
    };

}
