/*
 * Generated by XDoclet - Do not edit!
 */
package com.mockrunner.example.jms.interfaces;

/**
 * Remote interface for PrintSession.
 */
public interface PrintSession
   extends javax.ejb.EJBObject
{

   public void sendMessage( java.lang.String customerId )
      throws java.rmi.RemoteException;

}
