/*
 * Generated by XDoclet - Do not edit!
 */
package com.mockrunner.example.jms.interfaces;

/**
 * Home interface for PrintSession.
 */
public interface PrintSessionHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/PrintSession";
   public static final String JNDI_NAME="com/mockrunner/example/PrintSession";

   public com.mockrunner.example.jms.interfaces.PrintSession create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
