/*
 * Generated by XDoclet - Do not edit!
 */
package com.mockrunner.example.ejb.interfaces;

/**
 * Home interface for BillEntity.
 */
public interface BillEntityHome
   extends javax.ejb.EJBHome
{
   String COMP_NAME="java:comp/env/ejb/BillEntity";
   String JNDI_NAME="com/mockrunner/example/UserEntity";

   com.mockrunner.example.ejb.interfaces.BillEntity create(java.lang.Integer id)
      throws javax.ejb.CreateException,java.rmi.RemoteException;

   java.util.Collection findUnpaid()
      throws javax.ejb.FinderException,java.rmi.RemoteException;

   java.util.Collection findAll()
      throws javax.ejb.FinderException,java.rmi.RemoteException;

   com.mockrunner.example.ejb.interfaces.BillEntity findByPrimaryKey(java.lang.Integer pk)
      throws javax.ejb.FinderException,java.rmi.RemoteException;

}
