/*
 * Generated by XDoclet - Do not edit!
 */
package com.mockrunner.example.ejb.interfaces;

/**
 * Remote interface for BillManagerSession.
 */
public interface BillManagerSession
   extends javax.ejb.EJBObject
{

   void markAsPaid()
      throws java.rmi.RemoteException;

}
