/*
 * Generated by XDoclet - Do not edit!
 */
package com.mockrunner.example.ejb.interfaces;

/**
 * Remote interface for PrintSession.
 */
public interface LogSession
   extends javax.ejb.EJBObject
{

   void createLogTable()
      throws java.rmi.RemoteException;

   void logMessage(java.lang.String message)
      throws java.rmi.RemoteException;

}
