/*
 * Generated by XDoclet - Do not edit!
 */
package com.mockrunner.example.ejb.interfaces;

/**
 * Home interface for UserLoginSession.
 */
public interface UserLoginSessionHome
   extends javax.ejb.EJBHome
{
   String COMP_NAME="java:comp/env/ejb/UserLoginSession";
   String JNDI_NAME="com/mockrunner/example/UserLoginSession";

   com.mockrunner.example.ejb.interfaces.UserLoginSession create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
