/*
 * Generated by XDoclet - Do not edit!
 */
package com.mockrunner.example.ejb.interfaces;

/**
 * Remote interface for UserEntity.
 */
public interface UserEntity
   extends javax.ejb.EJBObject
{

   java.lang.String getPassword()
      throws java.rmi.RemoteException;

   void setPassword(java.lang.String password)
      throws java.rmi.RemoteException;

   java.lang.String getUsername()
      throws java.rmi.RemoteException;

}
