/*
 * Generated by XDoclet - Do not edit!
 */
package com.mockrunner.example.ejb.interfaces;

/**
 * Remote interface for BillEntity.
 */
public interface BillEntity
   extends javax.ejb.EJBObject
{

   public java.lang.Integer getId(  )
      throws java.rmi.RemoteException;

   public java.util.Date getDate(  )
      throws java.rmi.RemoteException;

   public void setDate( java.util.Date date )
      throws java.rmi.RemoteException;

   public boolean getPaid(  )
      throws java.rmi.RemoteException;

   public void setPaid( boolean isPaid )
      throws java.rmi.RemoteException;

}
