/*
 * Generated by XDoclet - Do not edit!
 */
package com.mockrunner.example.ejb.interfaces;

/**
 * Remote interface for DBStateful.
 */
public interface DBStateful
   extends javax.ejb.EJBObject
{

   public void beginTransaction(  )
      throws java.rmi.RemoteException;

   public void executeSQL( java.lang.String sql )
      throws java.rmi.RemoteException;

   public void endTransaction( boolean commit )
      throws java.rmi.RemoteException;

}
