/*
 * Generated by XDoclet - Do not edit!
 */
package com.mockrunner.example.ejb.interfaces;

/**
 * Home interface for LogSession.
 */
public interface LogSessionHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/LogSession";
   public static final String JNDI_NAME="com/mockrunner/example/LogSession";

   public com.mockrunner.example.ejb.interfaces.LogSession create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
