/*
 * Generated by XDoclet - Do not edit!
 */
package com.mockrunner.example.ejb.interfaces;

/**
 * Remote interface for PaySession.
 */
public interface PaySession
   extends javax.ejb.EJBObject
{

   public void payBill( java.lang.String customerId,java.lang.String billId,double amount )
      throws com.mockrunner.example.ejb.PaySessionException, java.rmi.RemoteException;

}
