/*
 * Generated by XDoclet - Do not edit!
 */
package com.mockrunner.example.ejb.interfaces;

/**
 * Remote interface for UserEntity.
 */
public interface UserEntity
   extends javax.ejb.EJBObject
{

   public java.lang.String getPassword(  )
      throws java.rmi.RemoteException;

   public void setPassword( java.lang.String password )
      throws java.rmi.RemoteException;

   public java.lang.String getUsername(  )
      throws java.rmi.RemoteException;

}
